
DOMException {line: 2, column: 218742, sourceURL: "https://50990f59-a96c-4309-8167-0c1080ebea7b-00-2alhioy68tcv0.riker.replit.dev/__replco/static/devt…"}
column: 218742
line: 2
sourceURL: "https://50990f59-a96c-4309-8167-0c1080ebea7b-00-2alhioy68tcv0.riker.replit.dev/__replco/static/devtools/eruda/3.2.3/eruda.js"
stack: "WebSocket@[native code]↵t@https://50990f59-a96c-4309-8167-0c1080ebea7b-00-2alhioy68tcv0.riker.replit.dev/__replco/static/devtools/eruda/3.2.3/eruda.js:2:218742↵setupWebSocket@https://50990f59-a96c-4309-8167-0c1080ebea7b-00-2alhioy68tcv0.riker.replit.dev/@vite/client:536:32↵fallback@https://50990f59-a96c-4309-8167-0c1080ebea7b-00-2alhioy68tcv0.riker.replit.dev/@vite/client:509:30↵@https://50990f59-a96c-4309-8167-0c1080ebea7b-00-2alhioy68tcv0.riker.replit.dev/@vite/client:555:25↵@https://50990f59-a96c-4309-8167-0c1080ebea7b-00-2alhioy68tcv0.riker.replit.dev/@vite/client:552:46"
[[Prototype]]: DOMException
ABORT_ERR: 20
DATA_CLONE_ERR: 25
DOMSTRING_SIZE_ERR: 2
HIERARCHY_REQUEST_ERR: 3
INDEX_SIZE_ERR: 1
INUSE_ATTRIBUTE_ERR: 10
INVALID_ACCESS_ERR: 15
INVALID_CHARACTER_ERR: 5
INVALID_MODIFICATION_ERR: 13
INVALID_NODE_TYPE_ERR: 24
INVALID_STATE_ERR: 11
NAMESPACE_ERR: 14
NETWORK_ERR: 19
NOT_FOUND_ERR: 8
NOT_SUPPORTED_ERR: 9
NO_DATA_ALLOWED_ERR: 6
NO_MODIFICATION_ALLOWED_ERR: 7
QUOTA_EXCEEDED_ERR: 22
SECURITY_ERR: 18
SYNTAX_ERR: 12
TIMEOUT_ERR: 23
TYPE_MISMATCH_ERR: 17
URL_MISMATCH_ERR: 21
VALIDATION_ERR: 16
WRONG_DOCUMENT_ERR: 4
code: 12
get code: ƒ code()
length: 0
name: "get code"
[[Prototype]]: ƒ ()
apply: ƒ apply()
arguments: "'arguments', 'callee', and 'caller' cannot be accessed in this context."
get arguments: ƒ arguments()
set arguments: ƒ arguments()
bind: ƒ bind()
call: ƒ call()
caller: "'arguments', 'callee', and 'caller' cannot be accessed in this context."
get caller: ƒ caller()
set caller: ƒ caller()
constructor: ƒ Function()
length: 0
name: "get code"
toString: ƒ toString()
Symbol(Symbol.hasInstance): undefined
[[Prototype]]: Object
message: "The string did not match the expected pattern."
get message: ƒ message()
length: 0
name: "get message"
[[Prototype]]: ƒ ()
apply: ƒ apply()
length: 2
name: "apply"
[[Prototype]]: ƒ ()
arguments: "'arguments', 'callee', and 'caller' cannot be accessed in this context."
get arguments: ƒ arguments()
length: 0
name: "get arguments"
[[Prototype]]: ƒ ()
set arguments: ƒ arguments()
length: 1
name: "set arguments"
[[Prototype]]: ƒ ()
bind: ƒ bind()
length: 1
name: "bind"
[[Prototype]]: ƒ ()
call: ƒ call()
length: 1
name: "call"
[[Prototype]]: ƒ ()
caller: "'arguments', 'callee', and 'caller' cannot be accessed in this context."
get caller: ƒ caller()
length: 0
name: "get caller"
[[Prototype]]: ƒ ()
set caller: ƒ caller()
length: 1
name: "set caller"
[[Prototype]]: ƒ ()
constructor: ƒ Function()
length: 1
name: "Function"
prototype: ƒ ()
[[Prototype]]: ƒ ()
length: 0
name: "get code"
toString: ƒ toString()
length: 0
name: "toString"
[[Prototype]]: ƒ ()
Symbol(Symbol.hasInstance): undefined
[[Prototype]]: Object
constructor: ƒ Function()
hasOwnProperty: ƒ hasOwnProperty()
isPrototypeOf: ƒ isPrototypeOf()
propertyIsEnumerable: ƒ propertyIsEnumerable()
toLocaleString: ƒ toLocaleString()
toString: ƒ toString()
valueOf: ƒ valueOf()
__defineGetter__: ƒ __defineGetter__()
__defineSetter__: ƒ __defineSetter__()
__lookupGetter__: ƒ __lookupGetter__()
__lookupSetter__: ƒ __lookupSetter__()
__proto__: ƒ ()
get __proto__: ƒ get __proto__()
set __proto__: ƒ set __proto__()
name: "SyntaxError"
get name: ƒ name()
length: 0
name: "get name"
[[Prototype]]: ƒ ()
apply: ƒ apply()
arguments: "'arguments', 'callee', and 'caller' cannot be accessed in this context."
get arguments: ƒ arguments()
set arguments: ƒ arguments()
bind: ƒ bind()
call: ƒ call()
caller: "'arguments', 'callee', and 'caller' cannot be accessed in this context."
get caller: ƒ caller()
set caller: ƒ caller()
constructor: ƒ Function()
length: 0
name: "get code"
toString: ƒ toString()
Symbol(Symbol.hasInstance): undefined
[[Prototype]]: Object
constructor: ƒ DOMException()
ABORT_ERR: 20
DATA_CLONE_ERR: 25
DOMSTRING_SIZE_ERR: 2
HIERARCHY_REQUEST_ERR: 3
INDEX_SIZE_ERR: 1
INUSE_ATTRIBUTE_ERR: 10
INVALID_ACCESS_ERR: 15
INVALID_CHARACTER_ERR: 5
INVALID_MODIFICATION_ERR: 13
INVALID_NODE_TYPE_ERR: 24
INVALID_STATE_ERR: 11
NAMESPACE_ERR: 14
NETWORK_ERR: 19
NOT_FOUND_ERR: 8
NOT_SUPPORTED_ERR: 9
NO_DATA_ALLOWED_ERR: 6
NO_MODIFICATION_ALLOWED_ERR: 7
QUOTA_EXCEEDED_ERR: 22
SECURITY_ERR: 18
SYNTAX_ERR: 12
TIMEOUT_ERR: 23
TYPE_MISMATCH_ERR: 17
URL_MISMATCH_ERR: 21
VALIDATION_ERR: 16
WRONG_DOCUMENT_ERR: 4
length: 0
name: "DOMException"
prototype: DOMException
[[Prototype]]: ƒ ()
Symbol(Symbol.toStringTag): undefined
[[Prototype]]: Object
constructor: ƒ DOMException()
message: "The string did not match the expected pattern."
name: "SyntaxError"
toString: ƒ toString()
[[Prototype]]: Object